// Type for time slot
export interface TimeSlot {
    start_time: string;
    end_time: string;
}

// Enum for days of the week
export type DayOfWeek = 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday';

// Enum for session types
export type SessionType = 'general' | 'vocational' | 'P5';

// Enum for semester
export type Semester = '1' | '2';

// Main schedule interface
export interface Schedule {
    _id?: string;  // MongoDB ID is optional as it's generated by the database
    class_name: string;
    subject: string;
    teacher: string;
    day_of_week: DayOfWeek;
    time_slot: TimeSlot;
    room: string;
    session_type: SessionType;
    semester: Semester;
    academic_year: string;
}
